using System.Linq;
using System.Numerics;
using Content.Client.Administration.Managers;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        private List<(string, NetEntity?)> _warps = new();
        private string _searchText = string.Empty;

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;

            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
        }

        public void UpdateWarps(IEnumerable<GhostWarp> warps)
        {
            var adminManager = IoCManager.Resolve<IClientAdminManager>();
            var isAdmin = adminManager.IsAdmin();

            var sortedWarps = warps
                .Where(w => w.WarpKind != GhostStatus.CryoSleep || isAdmin)
                .OrderBy(w => w.IsWarpPoint)
                .ThenBy(w => w.AdminOnly)
                .ThenBy(w => w.WarpKind)
                .ThenBy(w => w.DisplayName, StringComparer.Ordinal)
                .ToList();

            _warps = new List<(string, NetEntity?)>();
            string? lastGroup = null;
            foreach (var w in sortedWarps)
            {
                string currentGroup = w.IsWarpPoint ? "WarpPoint" : w.WarpKind.ToString();
                if (currentGroup != lastGroup && lastGroup != null)
                {
                    string dividerText = GetDividerText(w);
                    _warps.Add((dividerText, null));
                }
                _warps.Add((GetWarpName(w), w.Entity));
                lastGroup = currentGroup;
            }
        }

        private string GetWarpName(GhostWarp w)
        {
            if (w.IsWarpPoint)
                return $"Warp: {w.DisplayName}";

            if (string.IsNullOrEmpty(w.JobName))
                w.JobName = "Unknown";

            var baseKey = w.DupeNumber > 0 ? "-dupe" : "";
            var statusKey = w.WarpKind switch
            {
                GhostStatus.Dead => "dead",
                GhostStatus.Unconscious => "unconscious",
                GhostStatus.Ghost => "ghost",
                GhostStatus.CryoSleep => "cryo",
                GhostStatus.SSD => "ssd",
                _ => "current",
            };

            return Loc.GetString(
                $"ghost-target-window-warp-button-{statusKey}{baseKey}",
                ("name", w.DisplayName),
                ("job", w.JobName),
                ("dupe", w.DupeNumber));
        }

        private string GetDividerText(GhostWarp w)
        {
            if (w.IsWarpPoint)
                return "============WARP POINTS============";

            var statusKey = w.WarpKind switch
            {
                GhostStatus.Dead => "DEAD",
                GhostStatus.Unconscious => "UNCONSCIOUS",
                GhostStatus.Ghost => "GHOST",
                GhostStatus.CryoSleep => "CRYO",
                GhostStatus.SSD => "SSD",
                _ => "CURRENT",
            };

            return $"============{statusKey}============";
        }

        public void Populate()
        {
            ButtonContainer.DisposeAllChildren();
            AddButtons();
        }

        private void AddButtons()
        {
            foreach (var (name, warpTarget) in _warps)
            {
                if (warpTarget == null)
                {
                    var label = new Label
                    {
                        Text = name,
                        HorizontalAlignment = HAlignment.Center,
                    };
                    ButtonContainer.AddChild(label);
                    continue;
                }

                if (string.IsNullOrEmpty(name) || warpTarget == NetEntity.Invalid)
                    continue;

                var currentButtonRef = new Button
                {
                    Text = name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Stretch,
                    VerticalAlignment = VAlignment.Center,
                    SizeFlagsStretchRatio = 1,
                    ClipText = true,
                };

                currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warpTarget.Value);
                currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

                ButtonContainer.AddChild(currentButtonRef);
            }
        }

        private bool ButtonIsVisible(Button button)
        {
            return string.IsNullOrEmpty(_searchText) || button.Text == null || button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
        }

        private void UpdateVisibleButtons()
        {
            foreach (var child in ButtonContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;

            UpdateVisibleButtons();
            // Reset scroll bar so they can see the relevant results.
            GhostScroll.SetScrollValue(Vector2.Zero);
        }
    }
}
