- type: entity
  id: DonkcoServiceTechFabCircuitboard
  parent: ServiceTechFabCircuitboard
  name: donk co service techfab machine board
  description: A machine printed circuit board for a donk co service techfab
  components:
    - type: MachineBoard
      prototype: DonkcoServiceTechFab
